require:
  # - rubocop-performance
  - rubocop-rails

AllCops:
  CacheRootDirectory: 'tmp/cache'
  Exclude:
    - 'bin/*'
    - 'db/schema.rb'
    - 'vendor/**/*'
    - 'node_modules/**/*'
  TargetRubyVersion: 2.6
  TargetRailsVersion: 5.0

Bundler:
  Enabled: true

Layout/AccessModifierIndentation:
  EnforcedStyle: indent
  SupportedStyles:
    - outdent
    - indent

Layout/HashAlignment:
  EnforcedHashRocketStyle: key
  EnforcedColonStyle: key
  EnforcedLastArgumentHashStyle: always_inspect

Layout/ParameterAlignment:
  EnforcedStyle: with_fixed_indentation

Layout/EmptyLinesAroundArguments:
  Enabled: true

Layout/EmptyLinesAroundClassBody:
  EnforcedStyle: empty_lines_except_namespace

Layout/EmptyLinesAroundModuleBody:
  EnforcedStyle: empty_lines_except_namespace

Layout/EndAlignment:
  AutoCorrect: true

Layout/ExtraSpacing:
  AllowForAlignment: true

Layout/FirstArrayElementLineBreak:
  Enabled: true

Layout/FirstHashElementLineBreak:
  Enabled: true

Layout/FirstMethodArgumentLineBreak:
  Enabled: true

Layout/FirstArgumentIndentation:
  EnforcedStyle: consistent

Layout/FirstArrayElementIndentation:
  EnforcedStyle: consistent

Layout/FirstHashElementIndentation:
  EnforcedStyle: consistent

Layout/MultilineAssignmentLayout:
  Enabled: true
  EnforcedStyle: new_line

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Layout/MultilineOperationIndentation:
  EnforcedStyle: indented

Layout/SpaceAroundOperators:
  AllowForAlignment: true

Layout/SpaceAroundMethodCallOperator:
  Enabled: true

Layout/SpaceBeforeFirstArg:
  AllowForAlignment: false

Lint/AmbiguousBlockAssociation:
  Exclude:
    - "spec/**/*"

Lint/BigDecimalNew:
  Enabled: true # todo

# Lint/DeprecatedOpenSSLConstant:
#   Enabled: true

Lint/RaiseException:
  Enabled: true

Lint/RedundantWithIndex:
  Enabled: true

Lint/StructNewOverride:
  Enabled: true

Lint/UnusedMethodArgument:
  AllowUnusedKeywordArguments: true
  IgnoreEmptyMethods: true

Metrics/AbcSize:
  Enabled: false
  Max: 20 # default: 15

Metrics/BlockLength:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Naming/MethodParameterName:
  Enabled: false

Naming/VariableNumber:
  Enabled: false # TODO
  EnforcedStyle: snake_case

Rails/CreateTableWithTimestamps:
  Enabled: true
  Exclude:
    - "db/migrate/2018*"
    - "db/migrate/2019*"
    - "db/migrate/20200*"

Rails/DynamicFindBy:
  Enabled: false

Rails/FilePath:
  Enabled: false

Rails/HasAndBelongsToMany:
  Enabled: false # TODO

Rails/HasManyOrHasOneDependent:
  Enabled: false # TODO

Rails/NotNullColumn:
  Enabled: true
  Exclude:
    - "db/migrate/2018*"
    - "db/migrate/2019*"
    - "db/migrate/20200*"

Rails/Output:
  Enabled: true
  Exclude:
    - "db/**/*"
    - "config/**/*"

Rails/OutputSafety:
  Enabled: false # TODO

Rails/ReversibleMigration:
  Enabled: true
  Exclude:
    - "db/migrate/2018*"
    - "db/migrate/2019*"
    - "db/migrate/20200*"

Rails/SkipsModelValidations:
  Enabled: true
  Exclude:
    - "db/migrate/*"
    - "lib/tasks/**/*"

Rails/UniqueValidationWithoutIndex:
  Enabled: false # TODO

Rails/UnknownEnv:
  Enabled: false # TODO: Use something other than RAILS_ENV for sandbox/staging

Style/AccessModifierDeclarations:
  Enabled: true

Style/AsciiComments:
  Enabled: false

Style/AndOr:
  Enabled: true
  EnforcedStyle: conditionals

Style/BlockDelimiters:
  Enabled: true
  Exclude:
    - "spec/**/*"

Style/Dir:
  Enabled: true

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: true

Style/FloatDivision:
  Enabled: false

Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true

Style/Lambda:
  Enabled: false

Style/MethodCallWithArgsParentheses:
  Enabled: true # false by default
  Exclude:
    - "config/routes.rb"
    - "config/routes/*"
    - "Gemfile"
    - "spec/factories/**/*"
  IgnoreMacros: true
  IgnoredMethods:
    - include
    - load
    - print
    - private
    - protected
    - public
    - puts
    - raise
    - require
    - require_relative
    # rake
    - desc
    - namespace
    - task
    # rspec
    - after
    - and
    - around
    - before
    - context
    - describe
    - include_context
    - include_example
    - include_examples
    - it
    - it_behaves_like
    - not_to
    - shared_context
    - shared_examples
    - shared_examples_for
    - specify
    - to
    - to_not
    # swagger
    - key
    - operation
    - property
    - response
    - security_definition
    - swagger_path
    - swagger_schema

Style/ModuleFunction:
  Enabled: true

Style/ReturnNil:
  Enabled: true

Style/SignalException:
  EnforcedStyle: only_raise

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: single_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: single_quotes

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: no_comma

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma

#
# Temporary disabled
#

Layout/LineLength:
  Enabled: false # TODO
  Max: 100 # default: 80

Lint/IneffectiveAccessModifier:
  Enabled: true

Lint/MissingCopEnableDirective:
  Enabled: true

Lint/RescueException:
  Enabled: true

Lint/ShadowedException:
  Enabled: true

Metrics/BlockNesting:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/ModuleLength:
  Enabled: false

Metrics/ParameterLists:
  Enabled: false

Naming/AccessorMethodName:
  Enabled: false
  Exclude:
    - "spec/**/*"

Naming/MemoizedInstanceVariableName:
  Enabled: false # TODO
  EnforcedStyleForLeadingUnderscores: required

Naming/PredicateName:
  Enabled: false
  Exclude:
    - "spec/**/*"

Security/Eval:
  Enabled: true

Security/Open:
  Enabled: true

Style/ClassAndModuleChildren:
  Enabled: false
  Exclude:
    - "spec/**/*"

Style/ClassVars:
  Enabled: true
  Exclude:
    - "spec/**/*"

Style/DateTime:
  Enabled: false

Style/ExpandPathArguments:
  Enabled: true

Style/ExponentialNotation:
  Enabled: true

Style/FormatStringToken:
  Enabled: true
  Exclude:
    - "config/routes.rb"

Style/GuardClause:
  Enabled: true

Style/MixinUsage:
  Enabled: true

Style/NumericPredicate:
  Enabled: false # TODO
  Exclude:
    - "spec/**/*"

Style/SafeNavigation:
  Enabled: true

Style/StructInheritance:
  Enabled: true
  Exclude:
    - "spec/**/*"
